local mod = dmhub.GetModLoading()

local AI = rawget(_G, "DirectorTacticsAI")
if AI == nil or AI._internal == nil then
    error("DirectorTacticsAI.lua must be loaded before this DirectorTactics subsystem")
end

local K = AI.K or {}
AI.K = K

local function EnsureDomain(name)
    K[name] = K[name] or {}
    return K[name]
end

local function SetDefault(domain, key, value)
    if domain[key] == nil then
        domain[key] = value
    end
end

local Candidate = EnsureDomain("Candidate")
SetDefault(Candidate, "ActorSelectionThreshold", 0.8)
SetDefault(Candidate, "ActorSelectionAfterSpendThreshold", 4)
SetDefault(Candidate, "AdvancePromotionThreshold", 0.8)
SetDefault(Candidate, "AreaMainActionPromotionMargin", 3)
SetDefault(Candidate, "LogLimit", 12)
SetDefault(Candidate, "MaliceResourceThresholdCostDiscount", 0.5)
SetDefault(Candidate, "MovementOnlyMinimumScoreDelta", 0.75)
SetDefault(Candidate, "MovementOscillationHighValueOverride", 3)
SetDefault(Candidate, "MovementOscillationPenalty", 2.5)
SetDefault(Candidate, "PlayActorIterationCap", 5)
SetDefault(Candidate, "StartTurnMaliceThresholdMinimum", 1)
SetDefault(Candidate, "StartTurnMaliceThresholdMultiplier", 0.5)
SetDefault(Candidate, "StartTurnMaliceReservationMinimumScore", 6)
SetDefault(Candidate, "TransientExecutionRetryCap", 2)
SetDefault(Candidate, "TriggerDispatchCap", 3)
SetDefault(Candidate, "TriggerPositiveThreshold", 0)
SetDefault(Candidate, "TriggerRetryCooldownSeconds", 5)

local Score = EnsureDomain("Score")
SetDefault(Score, "AllyDoctrineMultiplier", 0.8)
SetDefault(Score, "AreaOverkillCap", 6)
SetDefault(Score, "AreaOverkillMultiplier", 0.15)
SetDefault(Score, "AreaMainPressureBonus", 1.5)
SetDefault(Score, "BlockedTargetPenalty", -100)
SetDefault(Score, "BleedingRiskPenalty", -2)
SetDefault(Score, "BruteClusterMultiplier", 0.8)
SetDefault(Score, "ComboLookaheadCap", 4)
SetDefault(Score, "ComboLookaheadMinimumDelta", 0.5)
SetDefault(Score, "ComboLookaheadMultiplier", 1)
SetDefault(Score, "ControlledTargetFollowupBonus", 2)
SetDefault(Score, "EndRoundVillainTimingBonus", 4)
SetDefault(Score, "FinishBonus", 6)
SetDefault(Score, "FocusCap", 3)
SetDefault(Score, "FocusMissingStaminaMultiplier", 0.08)
SetDefault(Score, "ForcedMoveFallCap", 12)
SetDefault(Score, "ForcedMoveFallMultiplier", 3)
SetDefault(Score, "ForcedMoveDestinationCap", 8)
SetDefault(Score, "ForcedMoveDestinationMultiplier", 0.6)
SetDefault(Score, "ForcedMoveFriendlyFallCap", 18)
SetDefault(Score, "ForcedMoveFriendlyFallMultiplier", 4)
SetDefault(Score, "GrabObjectiveControlBonus", 1.2)
SetDefault(Score, "GrabNearbyEnemyControlBonus", 0.4)
SetDefault(Score, "GrabDefaultControlBonus", 0.4)
SetDefault(Score, "FriendlyFireMultiplier", -3)
SetDefault(Score, "FrightenedSourceAttackBonus", 1.5)
SetDefault(Score, "FrightenedSourceBanePenalty", -1.5)
SetDefault(Score, "InvalidForcedMovePenalty", -8)
SetDefault(Score, "MaliceCostPriorityMultiplier", 0.45)
SetDefault(Score, "MaliceDifficultyMultiplier", 4)
SetDefault(Score, "MaliceImpactBase", 2)
SetDefault(Score, "MaliceImpactCostCap", 6)
SetDefault(Score, "MaliceImpactCostMultiplier", 0.5)
SetDefault(Score, "MalicePriorityMinimumWeight", 0.35)
SetDefault(Score, "MaliceUnavailablePenalty", -100)
SetDefault(Score, "ManualPromptBase", 4)
SetDefault(Score, "ManualTargetingBonus", 2)
SetDefault(Score, "MultiTargetBonus", 2)
SetDefault(Score, "PendingLethalPenalty", -5)
SetDefault(Score, "PendingOngoingCap", 2)
SetDefault(Score, "PendingOngoingMultiplier", 0.1)
SetDefault(Score, "PressureBonus", 2)
SetDefault(Score, "PressureDamageMultiplier", 1.5)
SetDefault(Score, "ProneMeleeTargetBonus", 1.5)
SetDefault(Score, "ProneStrikePenalty", -1.5)
SetDefault(Score, "RestrainedTargetBonus", 1.5)
SetDefault(Score, "SignatureBonus", 6)
SetDefault(Score, "SoloLateVillainBonus", 3)
SetDefault(Score, "SpecialMaliceManualBonus", 3)
SetDefault(Score, "ShiftEngagedBonus", 2.5)
SetDefault(Score, "ShiftEscapeThreatBonus", 2)
SetDefault(Score, "EscapeGrabBase", 14)
SetDefault(Score, "HideAmbushBase", 4)
SetDefault(Score, "SearchHiddenBase", 10)
SetDefault(Score, "AidAttackAllyPayoffBonus", 3)
SetDefault(Score, "StartTurnBrutalEffectivenessBase", 3)
SetDefault(Score, "StartTurnBrutalEffectivenessRoleBonus", 2)
SetDefault(Score, "StartTurnFallbackScore", 1)
SetDefault(Score, "StartTurnMaliceCostMultiplier", 0.35)
SetDefault(Score, "StartTurnMaliceWeightMultiplier", 1.5)
SetDefault(Score, "StartTurnMaliciousStrikeBase", 4)
SetDefault(Score, "StrikeBonus", 2)
SetDefault(Score, "TauntedOffTargetPenalty", -8)
SetDefault(Score, "WeakenedPowerRollPenalty", -1.5)
SetDefault(Score, "VillainActionBase", 8)
SetDefault(Score, "VillainPacingExpectedBonus", 2)
SetDefault(Score, "VillainPacingMissMultiplier", 1.5)

local Resource = EnsureDomain("Resource")
SetDefault(Resource, "DefaultCriticalThreshold", 19)

local Squad = EnsureDomain("Squad")
SetDefault(Squad, "DuplicatePenaltyDefault", 3)
SetDefault(Squad, "DuplicatePenaltyFocus", 0.8)

local Tactic = EnsureDomain("Tactic")
SetDefault(Tactic, "AmbusherFlankWeight", 2.4)
SetDefault(Tactic, "AidAttackEffectGuid", "e234f1f4-9953-43bd-894c-d96adbb63f84")
